# This is a basic workflow to help you get started with Actions

name: Labs-Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #- uses: actions/checkout@v2

    - name: Print Message
      run: echo hello from build!
  
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: print message
      run: echo Hello from deploy

    
